apiVersion: v1
kind: Pod
metadata:
        name: test-pod
        labels:
                app: test-pod
                image: 1.220.201.109:31002/nginx:latest
---
apiVersion: v1
kind: Service
metadata:
        name: test-svc
spec:
        selector:
                app: test-pod
        ports:
                - name: nginx
                  protocol: TCP
                  ports: 80
                  targetPort: 80
                  nodePort: 31008
        type: NodePort                  
